---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install pip module
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Check if bootstrap still works.
      ansible.builtin.include_role:
        name: buluma.bootstrap

    - name: Remove pip module
      ansible.builtin.pip:
        name: docker
        state: absent

    - name: Check if requested modules can be installed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: docker

    - name: Check if requested modules can be removed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: docker
            state: absent

    - name: Check if pyOpenSSL can be installed
      ansible.builtin.pip:
        name: pyOpenSSL
        state: present
      notify:
        - Remove pyOpenSSL

  handlers:

    - name: Remove pyOpenSSL
      ansible.builtin.pip:
        name: pyOpenSSL
        state: absent
